services:
  db:
    image: postgres:16.11-alpine3.23
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mcp_database
    ports:
      - "21001:5432"
    networks:
      - mcp_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
#Se conecta a la red creada en mcp_prueba/docker-compose.yaml
networks:
  mcp_network:
    external: true